### PR TITLE
Chef 14 post-migration fixes

### PR DESCRIPTION
**Pull request by detjensrobert**

### CODE REVIEW

**Review by ramereth — CHANGES_REQUESTED** [review]
Please remove the yum cookbook.

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by detjensrobert** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.3.0.  Have a nice day!

**Pull request merged**
