### PR TITLE
Install ibm-power-tools repo and install standard tools

### PR DESCRIPTION
**Pull request by ramereth**
TODO: Write serverspec tests for ppc64/ppc64le.

### CODE REVIEW

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs please review

**Review by lwillmeth — APPROVED** [review]
Passes rake and it looks like you checked everything in the recipe.  Looks good to me.

I like when tests cover the recipe from top to bottom like this.  It's a lot easier to check for full coverage.

**Review by lwillmeth — APPROVED** [review]
hm, it looks like my approved review doesn't count.  I guess I don't have write access.

**Comment by ramereth** [comment]
@lo9key I had forgotten to setup the teams properly. Looks like its working now. Thanks!

**Review by leel8on — APPROVED** [review]

**Comment by ramereth** [comment]
!bump major

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!

**Pull request merged**
