### PR TITLE
Chef 16 Fixes

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Chef 16: ibm-power](https://trello.com/c/f2sJzTFM/1945-chef-16-ibm-power)

**Review by ramereth — APPROVED** [review]
Please do a patch bump.

**Comment by zimmerry** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.4.2.  Have a nice day!

**Pull request merged**
