### PR TITLE
Chef 15 updates

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
[Chef 15: ibm-power](https://trello.com/c/HVvr3D7W/1690-chef-15-ibm-power)

**Comment by ramereth** [comment]
For some reason, the recent commit breaks ChefSpec. I'm working with upstream to see why that is.

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.4.0.  Have a nice day!

**Pull request merged**
