### PR TITLE
Updating ppc64-diag installation

### PR DESCRIPTION
**Pull request by hodgiwabi**
No edits

### CODE REVIEW

**Comment by ramereth** [comment]
@hodgesto ?

**Comment by hodgiwabi** [comment]
@ramereth Samar has told me to explore how I would get ppc64-diag installed properly on all powerpc images. You directed me here after I went through osuosl/base unnecessarily. Is this not the place that I would do that?

**Comment by ramereth** [comment]
I think based on what I mentioned in osuosl/openstack_taster#2 you might want to halt working on this until you, me and @knightsamar can discuss this more.

**Comment by hodgiwabi** [comment]
OK. I will wait for this. Maybe in Friday's meeting?

**Comment by ramereth** [comment]
@hodgesto we should probably discuss it before then as I'll be OoO on Friday.

**Comment by hodgiwabi** [comment]
closing this PR without merge based on our discussion.

**Pull request closed without merging**
